# Voir uniquement le mapping
curl -X GET "http://localhost:9200/avis/_mapping?pretty"

#Tous les documents (avec pagination)
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "from": 0,
  "size": 10,
  "query": { "match_all": {} }
}'

## Recherche simple sur "contenu_texte"
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "contenu_texte": "livraison rapide"
    }
  }
}'

# Rechercher dans le champ fulltext, champs créé pendant la phase du mapping, issue de: (titre + contenu)
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "fulltext": "expérience client"
    }
  }
}'

#Filtres, booléens et exact match, Documents avec 5 étoiles
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "term": {
      "nombre_etoile": 5
    }
  }
}'

# Combiner plusieurs conditions:
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "bool": {
      "must": [
        { "term": { "pays": "france" }},
        { "range": { "date_avis": { "gte": "2024-01-01" }}}
      ]
    }
  }
}'

##Agrégations et statistiques:

#Compter les avis par nombre d’étoiles:
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
    "par_etoiles": {
      "terms": { "field": "nombre_etoile" }
    }
  }
}'

#Compter les avis par pays:
curl -X GET "http://localhost:9200/avis/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
    "par_pays": {
      "terms": { "field": "pays" }
    }
  }
}'
